### ISSUE TITLE
Doc issue with second example

### ISSUE THREAD

**Issue by cfjedimaster** [WickyNilliams/cally#10]
On the home page, after the example on top, there is a Single Date section with text:

```
For a single date, use the <calendar-date> component, and place inside it a <calendar-month> component.
```

And then the next section is Date Range (https://wicky.nillia.ms/cally/#date-range) and it has the same text + sample code.

**Comment by WickyNilliams** [comment]
Thanks. That'll teach me not to copy and paste sections 😅 if you fancy making a PR the docs are under the `/docs` folder. Otherwise I'll fix tomorrow

**Comment by cfjedimaster** [comment]
I was curious what the syntax was, so, I don't know what the fix is. ;) But I'll take a quick look see.

**Comment by WickyNilliams** [comment]
I think it should just read

> For a date range, use the `<calendar-range>` component, and place inside it a `<calendar-month>` component.

**Comment by cfjedimaster** [comment]
Did you fix it already? I'm looking now and it looks right. It's possible I didn't read clearly as well.

**Comment by cfjedimaster** [comment]
Oh heh, yeah, it says 'for a single date'. Yes, I can do a quick pr.
