### ISSUE TITLE
How would you use it in React Js? And Styles

### ISSUE THREAD

**Issue by MarianoFfonseca** [WickyNilliams/cally#19]
### My questions
In your docs you are using `npm install cally` and then  saying you are importing it as `import "Cally"` put this its not working for me, do i import it as a object and how do i use it. 
How to i use the onChange on it?
And does it comes with styles?
### Why
Im really liking it but if i want to use it in production i have to know that thinks, thank you
Mariano!

**Comment by WickyNilliams** [comment]
Hey, did you see the guide here? https://wicky.nillia.ms/cally/guides/frameworks/#react

I will eventually add to the repo some examples that can be loaded up in stackblitz etc, but I haven't gotten around to it yet

**Comment by WickyNilliams** [comment]
Closing this for now, but happy to continue discussion if the docs have errors or anything is missing
