### ISSUE TITLE
Possible to use it with angular?

### ISSUE THREAD

**Issue by Ma77i** [WickyNilliams/cally#20]
Hi, I've been looking for a datepicker to use with angular and I haven't found anything worthwhile yet, I'm working with angular 16.

The html gives error in the web components, like:

'calendar-month' is not a known element

My question is, can it be used with angular or not yet?

**Comment by WickyNilliams** [comment]
I don't see why not. I haven't touched angular in a long time, but I think you need to "tell" it about web components. 

I guess the standard advice for consuming WCs in angular applies. You need CUSTOM_ELEMENTS_SCHEMA. This article explains it https://manuel-rauber.com/2021/02/23/youre-using-custom_elements_schema-wrong/

**Comment by WickyNilliams** [comment]
Closing this for now, but happy to discuss further
