### ISSUE TITLE
First day of the Month Issue

### ISSUE THREAD

**Issue by wilcolinadev** [WickyNilliams/cally#44]
Hey there!

Just happened to notice on one of my projects that, the start of the week is not matching as expected, I thought it probably was a configuration issue on my site, however, I noticed the same problem in the official documentation example.

For example, June, 1st 2024 should be a Saturday while the Calendar is displaying that day as a Sunday.

Let me know if it could just be something related to my time, or if it might be an issue with the utils or even better just an issue on my end.

Thank you for taking a look!

Reference Screenshots below 

![Screenshot 2024-05-22 at 8 43 06 PM](https://github.com/WickyNilliams/cally/assets/56809033/37dbb5c1-3ded-4211-9a2a-e4307f71a0f1)
![Screenshot 2024-05-22 at 8 43 21 PM](https://github.com/WickyNilliams/cally/assets/56809033/00df2870-accd-451a-bdc0-9bfa8f6b46ee)

**Comment by WickyNilliams** [comment]
Oh that's weird. Seems related to #18

Did you change anything in the above screenshot to show Tuesday as first day of the week? Seems like an off by one error somehow. 

May I ask what timezone you are in?

**Comment by wilcolinadev** [comment]
No, I did not change anything in the screenshots. It seems to be fine just now, but I have already seen it happen twice during the past two evenings, which is definitely making me think that it could be a timezone issue. 

I am located in Central Daylight Time GMT-5

**Comment by WickyNilliams** [comment]
Thanks for the info. Yeah must be related to timezone. Can you give some info on browser (+ version) and OS please?

**Comment by WickyNilliams** [comment]
I noticed there were some places I wasn't using `getUTC*`/`setUTC*` methods on Date. I have fixed those up now, and released as `0.6.1`. I'm hoping that fixes things for you. Can you check (around the same time you observed the bug?) and report back please. You might want to clear you browser cache to be sure you're getting the latest version from the docs

**Comment by wilcolinadev** [comment]
Hey, thanks a lot for checking on that, I will keep an eye on it today, and if I see something weird I will let you know.

**Comment by WickyNilliams** [comment]
Appreciate it! I'll reopen this issue for now pending your feedback

**Comment by wilcolinadev** [comment]
I looked it up over the past two days and I did not see the bug, so it looks like that was the issue,thanks a lot for looking into it so quickly, take care!

**Comment by WickyNilliams** [comment]
Great! Glad to hear. Hopefully that's the last of the bugs related to this. It really is an uphill battle to prevent JS printing dates in user's timezone
