### ISSUE TITLE
"today" calculated relative to UTC rather than system time

### ISSUE THREAD

**Issue by MatiasWettstein** [WickyNilliams/cally#56]
Can we define the default time zone for the calendar?

For example, in the calendar, I have the "today" part, but in my case, I need to set the default TZ at UTC-3, because it detects the next day at 9:00 PM of the current day.

Is this something that is planned to be implemented into cally?

Thanks!

**Comment by WickyNilliams** [comment]
Just to be sure what you are saying: you are seeing the css part `today` being applied to the wrong date?

If so, I think this is a bug and should be fixed, rather than exposing some timezone property

**Comment by MatiasWettstein** [comment]
Yes, for example in my case I'm in the UTC-3 zone and when I use the calendar after 9 PM the CSS part `today` indicates the next day, I assume it is because it detects the 00:00 of the next day.

**Comment by WickyNilliams** [comment]
Got it! Sounds like a bug then. I think it's calculating today based on UTC time. I can change this to make the calculation relative to system time instead.

**Comment by WickyNilliams** [comment]
@gavrichards I had some spare time, and the fix turned out to be simple (at least in my testing). Will release momentarily

**Comment by gavrichards** [comment]
Oh fantastic, thank you so much!

**Comment by WickyNilliams** [comment]
Try `v0.7.2`!

**Comment by gavrichards** [comment]
I can confirm it's working nicely, thank you again.

**Comment by WickyNilliams** [comment]
Glad to hear! Excuse the delay :)
