### ISSUE TITLE
Start week with Sunday 

### ISSUE THREAD

**Issue by jdegand** [WickyNilliams/cally#58]
![cally](https://github.com/user-attachments/assets/561edee4-67da-4f16-9611-07c968c3eebc)

I looked into issues like #44 and it still seems like something is off.   Or you need to add extra logic to do this.

**Comment by WickyNilliams** [comment]
Am i missing something? This looks correct to me. Can you share your code?

**Comment by jdegand** [comment]
Calendars typically have `SMTWTFS` format.  In the screenshot above, it is `MTWTFSS`.   The calendar does start on the correct day, but having this format is unnatural.

**Comment by WickyNilliams** [comment]
Sunday is not a universal choice for first day of the week. It varies by country and culture, though is typically either Monday, Sunday, or Saturday. 

Cally considers Monday to be the first day of the week. This aligns with the [ISO 8601](https://en.wikipedia.org/wiki/ISO_week_date) standard. 

It is mentioned in the docs here: https://wicky.nillia.ms/cally/components/calendar-range/#properties-and-attributes

I'll close this for now, but am happy to discuss further

**Comment by WickyNilliams** [comment]
What could be considered a bug here is that i've not aligned with ISO standard when it comes to numbering days of the week. Rather I've followed what JS' `Date` does. 

Perhaps I should change this to be [1, 7] (mon - sun) rather than [0, 6] (sun - sat)
