### ISSUE TITLE
Example on home page not rendering properly on Firefox desktop

### ISSUE THREAD

**Issue by sponsfreixes** [WickyNilliams/cally#6]
I found the [documentation website](https://wicky.nillia.ms/cally/) first on my phone using Firefox. Then I opened it on my laptop, and noticed it showed differently. Then I opened it with Chrome on Desktop, and it looks like the rendering on Firefox Desktop is the one off. The selected background color is black instead of red, the arrows to change month do not show, and the two months do not show side to side even if the screen is wide enough. Better an image than words:

![image](https://github.com/WickyNilliams/cally/assets/1104773/5afd9d49-9d00-4a83-983f-3b9b39ebf515)

I haven't had the opportunity to try on another computer yet, I'll try to do that later.

**Comment by WickyNilliams** [comment]
Are you using an outdated FF on desktop? I'm a FF user on both mobile and desktop, so it's one browser that should have no rendering bugs 😅 I suspect it's an old version, which doesn't support css nesting (which I use in the docs, but not the components themselves)?

Browser version and OS would be helpful. I might just remove the css nesting, someone else had issues with it also.

**Comment by sponsfreixes** [comment]
That's on FF 115.9.1esr (64-bit), Windows 11.

**Comment by WickyNilliams** [comment]
Thanks, can you check if this is now fixed? I have compiled away all CSS nesting, so i'm hoping it's resolved

**Comment by sponsfreixes** [comment]
Yes, that seems to have solved it! Thanks!

**Comment by WickyNilliams** [comment]
Awesome! Thanks for reporting back
