### ISSUE TITLE
Previous/Next buttons aren't fully accessible

### ISSUE THREAD

**Issue by rstoneIDBS** [WickyNilliams/cally#60]
I'm wrapping your excellent component inside a Lit element and providing override icons for the next/previous buttons. The Storybook a11y checker is identifying accessibility issues with the buttons as they don't have an aria-label or a tooltip. I'm not sure how this can be fixed in both an a11y and an i18n friendly way though, so don't have any suggestions or a PR I'm afraid :(

**Comment by WickyNilliams** [comment]
It should just be a case of adding an `aria-label` to your icons. See how it's done here with shoelace icons https://wicky.nillia.ms/cally/guides/usage/#calendar-components

**Comment by WickyNilliams** [comment]
This is something that needs solving your end. The buttons are labelled by default in Cally. So I will close, but happy to discuss further

**Comment by rstoneIDBS** [comment]
> This is something that needs solving your end. The buttons are labelled by default in Cally. So I will close, but happy to discuss further

Of course ! I was so focused on the buttons I didn't think of this, sorry for the wasted issue :)

**Comment by WickyNilliams** [comment]
No worries, easily done 👍
