### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by rstoneIDBS** [WickyNilliams/cally#61]
Cally currently supports localization of date formatting, but as far as I can tell it doesn't allow localization of the resources so days/months are always rendered in English. Supporting this would be a useful enhancement to an already great date picker component.

**Comment by WickyNilliams** [comment]
They get localised too, just set the `locale` attribute. For example to have it in Finnish

```html
<calendar-date locale="fi">
  <calendar-month></calendar-month>
</calendar-date>
```

See here https://codepen.io/WickyNilliams/pen/bGPOGgb

**Comment by rstoneIDBS** [comment]
That will teach me to use German as the locale in September ! I had forgotten how close some German & English words are ;)

**Comment by rstoneIDBS** [comment]
However, if I set my browser locale to be non English (French in this case), Cally isn't picking this up - is this by design? The docs say "The locale for formatting dates. If not set, will use the browser's locale"

**Comment by WickyNilliams** [comment]
Hmm it might be that the browser gets its locale from the OS despite its own settings. 

Essentially if `locale` is not passed to Cally then we create a formatter like `new Intl.DateTimeFormat(undefined, options)`. And then it resolves to whatever the browser decides to be the locale. 

Maybe I should link to the MDN page for this from the docs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#locales
