### ISSUE TITLE
Feat: Make weekday name length configurable

### ISSUE THREAD

**Issue by raphaelokon** [WickyNilliams/cally#66]
I think it would be feasible to let the `shortDayName` be configurable between 'narrow' | 'short'? → https://github.com/WickyNilliams/cally/blob/main/src/calendar-month/useCalendarMonth.ts#L21

**Comment by WickyNilliams** [comment]
Just realised this is a duplicate of #24. Closing in favour of that

**Comment by WickyNilliams** [comment]
Hey @raphaelokon this has now been published as part of `v0.8.0`. Sorry about the delay!
