### ISSUE TITLE
Weird select offset double digit cells

### ISSUE THREAD

**Issue by inlikealion** [WickyNilliams/cally#7]
Just saw this weird offset of the select highlight on double digit grid cells. Verified on Safari on iOS 17.4.1:

<img width="414" alt="image" src="https://github.com/WickyNilliams/cally/assets/347072/5eebfb85-5d64-4051-becd-9cf5ec4bdfb2">

Would you like any help exploring ways to have numbers remain centered in their cells? I’d love to do some css tinkering if you’d want it.

**Comment by WickyNilliams** [comment]
Oh huh! That's weird. I use `text-align: center` for the buttons so I'm surprised by that

By all means, go ahead. PRs are more than welcome!

**Comment by inlikealion** [comment]
@WickyNilliams cool. I’ll fire up an iOS simulator and see if I can get to the bottom of it shortly. Safari desktop (17.4.1) looks correct, btw.

**Comment by WickyNilliams** [comment]
OK i got the simulator working this end. Turns out it's because ios adding pretty hefty padding to buttons, which messed up the alignment. Should be fixed in `0.4.1`
